version: '3.7'
services:
  optimizerroach:
    container_name: optimizerroach
    hostname: optimizerroach
    image: cockroachdb/cockroach:latest-v22.1
    command: start-single-node --insecure --locality=region=us,zone=us-east
    ports:
      - '26257:26257'
      - '8080:8080'
    volumes:
      - 'optimizerroachdbdata:/cockroach/cockroach-data'
    networks:
      - optimizerroachnetwork
volumes:
  optimizerroachdbdata:
networks:
  optimizerroachnetwork:
