version: '3.7'
services:
  optimizeroracle21:
    container_name: optimizeroracle21
    hostname: optimizeroracle21
    image: ghcr.io/mkolumb/oracledb_pre:21.3-xe
    environment:
      - ORACLE_PWD=root
    ports:
      - '1521:1521'
      - '5500:5500'
    networks:
      - optimizeroracle21network
networks:
  optimizeroracle21network:
