version: '3.7'
services:
  optimizersqlserver:
    container_name: optimizersqlserver
    hostname: optimizersqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: yourStrong(!)Password
    ports:
      - '1401:1433'
    networks:
      - optimizersqlservernetwork
networks:
  optimizersqlservernetwork:
