name: Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - feature/initial
  pull_request:
    branches:
      - main
      - feature/initial
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v3

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install .NET SDK 6.0.301
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.301"

      - name: Install Dotnet Tools
        run: dotnet tool restore

      - name: Run Fake
        run: dotnet fake build
