name: Clean
'on':
  workflow_dispatch: null
jobs:
  build:
    name: Build
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Clean docker
        run: docker system prune --all --force
      - name: Clean docker
        run: docker volume prune --force
      - name: Clean workspace
        uses: AutoModality/action-clean@v1
      - name: Get the sources
        uses: actions/checkout@v3
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Clean unnecessary objects
        run: git clean -fdX
