name: Test Report
'on':
  workflow_run:
    workflows:
      - Build
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Optimizer tests
          path: '*.trx'
          reporter: dotnet-trx
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
