name: Upload Nuget
"on":
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - main
      - develop
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_VERSION: 6.0.301
  GITHUB_FEED: "https://nuget.pkg.github.com/mkolumb/index.json"
  GITHUB_USER: mkolumb
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
jobs:
  prerelease:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: nupkg
      - name: Push to GitHub Feed
        run: |
          for f in ./nupkg/*.nupkg
          do
            if [[ ${f} != *".symbols."* ]];then
              echo "Uploading package $f" to $GITHUB_FEED
              dotnet nuget push $f --api-key=$GITHUB_TOKEN --source=$GITHUB_FEED
            fi
            # curl -X PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED
          done
